### ISSUE TITLE
Update Status Page Styles - first-timers-only

### ISSUE THREAD

**Issue by nikolap994** [Evil-Bees/Alertit#23]
This is simple issue for those who want to see how Open Source work.

- Clone the project
- Visit http://localhost:3000/status
- Update some styles or change a class
- Make new Pull Request

Lets start working on open source together 😄

**Comment by canberkkoc1** [comment]
Hi, I would like to take on this task. This will be my first contribution.

**Comment by nikolap994** [comment]
You are welcome, let me know if I can help you with anything 👍🏻

**Comment by canberkkoc1** [comment]
Thanks, Am I free to make the changes we want? Is it only desired to make changes on the input and button on the status page?

**Comment by nikolap994** [comment]
You are welcome to do any changes you'd like on the status page.

**Comment by canberkkoc1** [comment]
I understand, thank you. 👍🏼

**Comment by macck7** [comment]
is issuse still open ???

**Comment by nikolap994** [comment]
@macck7  you are welcome to make any changes to this issue on the status page and make a PR 👍🏻

**Comment by macck7** [comment]
hi ,@nikolap994, on scrolling website, I have fond that, On clicking singup button page appears as in (image)...
I think, if they become parallel then, it will be better..
![image](https://user-images.githubusercontent.com/49000628/212326414-2cb9f40b-0570-4518-b9f8-03f9de970e91.png)

**Comment by nikolap994** [comment]
@macck7 Feel free to do any fixes on styles you'd like here 😄

**Comment by macck7** [comment]
@nikolap I have corrected the sigup page and sign in page And also added funtionality of eye button in passward field

**Comment by nikolap** [comment]
wrong nikolap 😉  
CC @nikolap994 ☝️

**Comment by ammarali0608** [comment]
![image](https://user-images.githubusercontent.com/89630572/212525124-08375767-aadb-446f-8a45-c1db08c4bd9f.png)

Here are some issues in the responsiveness of the screen

**Comment by nikolap994** [comment]
@ammarali0608  new issue is opened https://github.com/Evil-Bees/Alertit/issues/34

**Comment by ammarali0608** [comment]
> @nikolap994 I have corrected the sigup page and sign in page And also added funtionality of eye button in passward field ![image](https://user-images.githubusercontent.com/49000628/212351872-391b3aed-1232-420a-be32-b974a2167278.png)

is this merged in this repo or just on your repo? because this page is still not responsive

**Comment by nikolap994** [comment]
We are waiting for @cehicm to do the review.  She is the one in charge of frontend development😄 
https://github.com/Evil-Bees/Alertit/pull/36

**Comment by cehicm** [comment]
I've approved the PR @ammarali0608 , I've opened a new Issue for the text styles, if you want to take it up it's [here](https://github.com/Evil-Bees/Alertit/issues/38).
